### ISSUE TITLE
Hub also relies on PGPORT

### ISSUE THREAD

**Issue by jchampio** [greenplum-db/gpupgrade#118]
When running on 5432:

```
$ gpupgrade prepare start-hub
$ gpupgrade check config
20190911:18:31:42 gpupgrade_cli:gpadmin:mdw:015715-[ERROR]:-ERROR - gRPC call to hub failed
20190911:18:31:42 gpupgrade_cli:gpadmin:mdw:015715-[ERROR]:-rpc error: code = Unknown desc = could not retrieve cluster configuration: couldn't connect to cluster: could not connect to server: Connection refused
	Is the server running on host "localhost" and accepting
	TCP/IP connections on port 15432?
```

To get it working, you have to
```
$ PGPORT=5432 gpupgrade prepare start-hub
```

We should really just sanitize our entire environment and not rely on any of it. Ports, hosts, etc. should all be explicitly given or found using what the user has already told us.

**Comment by kalensk** [comment]
Seems like code has changed significantly from when this was created (ie: we no long have the prepare start-hub workflow, and use gpupgrade_config that specifies gphome_source, gphome_target, and source_master_port). Will re-open issue if encountered againe.
