### ISSUE TITLE
Agents don't respect GPUPGRADE_HOME; silently recreate state directories

### ISSUE THREAD

**Issue by jchampio** [greenplum-db/gpupgrade#127]
`GPUPGRADE_HOME` isn't passed via SSH, so all agents default to `~/.gpupgrade` even if the hub is using a different state directory. We haven't noticed until now because all agents will silently recreate that directory if it doesn't already exist.

**Comment by kalensk** [comment]
> all agents will silently recreate that directory if it doesn't already exist.

fun!  :/

**Comment by jchampio** [comment]
It gets better! When you have all segments running on a single host, sometimes the remote execution API will choose the master content ID to represent the host, and decide to run `bash` directly instead of `ssh`, so it will appear to "work" because the environment gets passed down.

I think this one of the things https://github.com/greenplum-db/gp-common-go-libs/pull/44 is intended to address...

**Comment by jmcatamney** [comment]
> I think this one of the things greenplum-db/gp-common-go-libs#44 is intended to address...

Indeed it is.  I'll be merging that PR once we're done with our current round of refactors, so we should get that fix soon.
