### ISSUE TITLE
Error during installation - wrong type for ExpectBegin method

### ISSUE THREAD

**Issue by baileygm** [greenplum-db/gpupgrade#174]
### Expected behavior
Clean installation without errors

### Actual behavior
Error during installation of gpupgrade
```# github.com/greenplum-db/gpupgrade/testutils
gpupgrade/src/github.com/greenplum-db/gpupgrade/testutils/sql.go:45:2: cannot use mock (type "github.com/DATA-DOG/go-sqlmock".Sqlmock) as type "gopkg.in/DATA-DOG/go-sqlmock.v1".Sqlmock in return argument:
	"github.com/DATA-DOG/go-sqlmock".Sqlmock does not implement "gopkg.in/DATA-DOG/go-sqlmock.v1".Sqlmock (wrong type for ExpectBegin method)
		have ExpectBegin() *"github.com/DATA-DOG/go-sqlmock".ExpectedBegin
		want ExpectBegin() *"gopkg.in/DATA-DOG/go-sqlmock.v1".ExpectedBegin
```
### Step to reproduce the behavior
go get github.com/greenplum-db/gpupgrade/...

**Comment by jchampio** [comment]
Hi @baileygm, thanks for the report! This project was started before Go modules existed, and it depends heavily on the `dep` workflow, so it can't be installed with a simple `go get` at the moment. But please reopen if the [installation procedure](https://github.com/greenplum-db/gpupgrade#build-and-test-the-upgrade-tool) doesn't work for you. (And keep in mind that this tool should not be used in production yet.)
