### ISSUE TITLE
gpupgrade_hub always occurs segmentation violation

### ISSUE THREAD

**Issue by zhangyuvip** [greenplum-db/gpupgrade#32]
Hi,
     Every time I execute the gpupgrade check disk-space command, gpupgrade_hub always occurs segmentation violation, as follows:
[yuzhang@h113 ~]$ go version
go version go1.10.3 linux/amd64

[yuzhang@h113 .gpupgrade]$ gpupgrade check disk-space  --master-host 192.168.2.113 --port 9432
20180713:10:48:45 gpupgrade_cli:yuzhang:h113:011835-[ERROR]:-ERROR - gRPC call to hub failed
Error: rpc error: code = Unavailable desc = transport is closing

20180713:10:48:45 gpupgrade_hub:yuzhang:h113:011828-[INFO]:-starting CheckDiskSpace
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x82f586]

goroutine 10 [running]:
github.com/greenplum-db/gpupgrade/utils.(*ClusterPair).GetHostnames(0xc4200c5f20, 0x17, 0x0, 0x0)
	/home/yuzhang/go_project/src/github.com/greenplum-db/gpupgrade/utils/cluster_pair.go:132 +0x96
github.com/greenplum-db/gpupgrade/hub/services.(*Hub).CheckDiskSpace(0xc4201c8070, 0xa2e580, 0xc4201d6660, 0xc42021e040, 0x0, 0x0, 0x0)
	/home/yuzhang/go_project/src/github.com/greenplum-db/gpupgrade/hub/services/hub_check_disk_space.go:24 +0x82
github.com/greenplum-db/gpupgrade/idl._CliToHub_CheckDiskSpace_Handler(0x9a9680, 0xc4201c8070, 0xa2e580, 0xc4201d6660, 0xc420222000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/yuzhang/go_project/src/github.com/greenplum-db/gpupgrade/idl/cli_to_hub.pb.go:1714 +0x241
google.golang.org/grpc.(*Server).processUnaryRPC(0xc4200f4dc0, 0xa30680, 0xc420001b00, 0xc420138780, 0xc4201d6150, 0xcdffc8, 0x0, 0x0, 0x0)
	/home/yuzhang/go_project/src/google.golang.org/grpc/server.go:920 +0x848
google.golang.org/grpc.(*Server).handleStream(0xc4200f4dc0, 0xa30680, 0xc420001b00, 0xc420138780, 0x0)
	/home/yuzhang/go_project/src/google.golang.org/grpc/server.go:1142 +0x1318
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420022770, 0xc4200f4dc0, 0xa30680, 0xc420001b00, 0xc420138780)
	/home/yuzhang/go_project/src/google.golang.org/grpc/server.go:637 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/yuzhang/go_project/src/google.golang.org/grpc/server.go:635 +0xa1

**Comment by nadeemg** [comment]
Can you try running these commands first:
gpupgrade check config
gpupgrade prepare start-agents

**Comment by jchampio** [comment]
@zhangyuvip Just so you're aware -- this tool is currently under *heavy* development. Don't use it in production yet! But if you'd like to help out with dev testing, that'd be awesome.

**Comment by zhangyuvip** [comment]
[yuzhang@CentOS64 .gpupgrade]$ gpupgrade check config --old-bindir /home/yuzhang/gpdb --master-host 192.168.20.117 --port 5432
20180716:02:56:46 gpupgrade_cli:yuzhang:CentOS64:063587-[INFO]:-Check config request is processed.

[yuzhang@CentOS64 .gpupgrade]$ ls
check-config  cluster_config.json  cluster_version.json  start-agents

[yuzhang@CentOS64 .gpupgrade]$ gpupgrade prepare start-agents
20180716:02:57:46 gpupgrade_cli:yuzhang:CentOS64:063600-[INFO]:-Started Agents in progress, check gpupgrade_agent logs for details

The agent command did not report an error, but did not see its process. 
[yuzhang@CentOS64 .gpupgrade]$ ps -ef|grep agent
yuzhang  63655 62209  0 03:04 pts/0    00:00:00 grep --color=auto agent
