### ISSUE TITLE
can't find the log file "tables_using_name.txt" 

### ISSUE THREAD

**Issue by weichangyong** [greenplum-db/gpupgrade#489]
**Describe the bug**
Initialize in progress.

Creating directories...                                            [COMPLETE]   
Starting gpupgrade hub process...                                  [COMPLETE]   
Saving source cluster configuration...                             [COMPLETE]   
Starting gpupgrade agent processes...                              [COMPLETE]   
Checking disk space...                                             [COMPLETE]   
Generating target cluster configuration...                         [COMPLETE]   
Creating target cluster...                                         [COMPLETE]   
Stopping target cluster...                                         [COMPLETE]   
Backing up target master...                                        [COMPLETE]   
Running pg_upgrade checks...                                       [FAILED]     

Error: initialize create cluster: InitializeCreateCluster: rpc error: code = Unknown desc = substep "CHECK_UPGRADE": 2 errors occurred:
	* upgrade primary segment on host gpmdw: rpc error: code = Unknown desc = upgrading primaries: 2 errors occurred:
	* check primary on host gpmdw with content 1: exit status 1
	* check primary on host gpmdw with content 0: exit status 1

	* upgrading master: Checking for invalid "name" user columns                    fatal

Your installation contains the "name" data type in user tables.  This
data type changed its internal alignment between your old and new
clusters so this cluster cannot currently be upgraded.  You can remove
the problem tables and restart the upgrade.  A list of the problem
columns is in the file:
    tables_using_name.txt

Failure, exiting: exit status 1

but I can't find this file tables_using_name.txt on current directory, where can I find this file ?

**To Reproduce**
gpupgrade initialize -f ./gpupgrade_config

**Expected behavior**

**Environment (please complete the following information):**
 - OS version: centos 7
 - go version:
 - greenplum version(s) (if applicable) greenplum-db-5.28.2

**Additional context**

**Comment by kalensk** [comment]
> but I can't find this file tables_using_name.txt on current directory, where can I find this file ?

Usually the file is located in `/home/gpadmin/.gpupgrade/pg_upgrade/seg-1`. That is, in the users home directory under `.gpupgrade`. We already have a fix that prints out the location of the file on error which has not yet been released.

We also have many [data migration scripts](https://github.com/greenplum-db/gpupgrade/tree/master/data_migration_scripts) to help people drop unsupported data types and re-create when possible after the upgrade. Run the generator script to generate the SQL to be used either 1) before upgrade (ie: `start`), 2) at the end of migration (ie: the `complete` directory), or 3) after reverting (ie: `revert`). Then use the executor script either before upgrade, after upgrade, or after reverting. This workflow is diagramed in the README under the `Steps` section.

**Comment by kalensk** [comment]
Hi @weichangyong did the above steps help? Any updates on this issue?
