### ISSUE TITLE
Error during initialize phase

### ISSUE THREAD

**Issue by macbethDGPH** [greenplum-db/gpupgrade#582]
There is some unrecognized error which occurred during init phase of gpupgrade.
All my attempts to find out what does it mean were failed.
Can I get some help (first of all, what does "exit status 127" mean)?  
```
$ gpupgrade initialize -avf gpupgrade_config 

Initialize in progress.

Initialize took 9ms

Error: could not determine source cluster version: exit status 127

NEXT ACTIONS
------------
Please address the above issue and run "gpupgrade initialize" again.
```

**Comment by kalensk** [comment]
There are logs in the following places that will reveal more information:
- /home/gpadmin/gpupgrade/...
- /home/gpadmin/...
- $MASTER_DATA_DIRECTORY/pg_log

Performing a Google search will reveal that exit status 127 means:
> Value 127 is returned by /bin/sh when the given command is not found within your PATH system variable and it is not a built-in shell command. In other words, the system doesn't understand your command, because it doesn't know where to find the binary you're trying to call.

See [here](https://stackoverflow.com/a/1763178) for example.

Those logs will probably reveal that the following command is attempting to be executed:
- Locally on the coordinator host `$GPHOME_SOURCE/bin/postgres --gp-version`
- And remotely on each host with `ssh -q <host> bash -c $GPHOME_SOURCE/bin/postgres --gp-version`

My suspicion is that the `source_gphome` set in the config file is incorrect, or not in the PATH for all hosts such that postgres is not being found. Alternatively, `ssh` might not be found on your system either.

Hope this helps!

**Comment by macbethDGPH** [comment]
Well, thank you for the answer
This is a version of the unitity
```
gpupgrade --version
Version: 1.1.0
Commit: b615d6f
Release: Open Source
```

> My suspicion is that the source_gphome set in the config file is incorrect, or not in the PATH for all hosts such that postgres is 
> not being found. Alternatively, ssh might not be found on your system either.
Your suspicion is wrong, cause if `source_gphome` was incorrect, than `gpupgrade` output would be some like that `could not determine source cluster version: fork/exec /path/to/the/postgres: no such file or directory`

**Comment by kalensk** [comment]
Well without knowing more information its pretty difficult to help. But that error is coming from when gpupgrade checks the minimum versions of GPDB as [indicated here](https://github.com/greenplum-db/gpupgrade/blob/039e97551b4b7057b324be6a574ca04d278caf9b/greenplum/allowed_gpdb_versions.go#L107-L109).

**Comment by macbethDGPH** [comment]
As I understand, when `gpupgrade` checks the versions, it runs `postgres --version` at the database paths. 
In my case there is `/opt/gpdb/bin/postgres` and `usr/local/greenplum-db/bin/postgres`.
When I run these command manually, I receive the following output
```
gpadmin@mdw:~$ /opt/gpdb/bin/postgres --version
postgres (Greenplum Database) 8.3.23
gpadmin@mdw:~$ /usr/local/greenplum-db/bin/postgres --version
postgres (Greenplum Database) 9.4.24
```
I will try to view gpupgrade's source code, but now i have no ideas why it doesn't work

**Comment by macbethDGPH** [comment]
[Line](https://github.com/greenplum-db/gpupgrade/blob/039e97551b4b7057b324be6a574ca04d278caf9b/greenplum/version.go#L67)

**Comment by macbethDGPH** [comment]
I've seen source code and have found place where version checking runs [here](https://github.com/greenplum-db/gpupgrade/blob/039e97551b4b7057b324be6a574ca04d278caf9b/greenplum/version.go#L58-L67)
But, in my case, host is ""(empty string) so `execCommand` runs followed command `gphome/bin/postgres --gp-version` where gphome - source path from `gpupgrade_config`

**Comment by macbethDGPH** [comment]
I assume there is some kind of "environment value problem". So I tried execute command `postgres --gp-version` by using `bash --login -c <command>`. I this case it works

**Comment by kalensk** [comment]
Im a quite confused, and struggling to offer help. Can you run the following commands on the coordinator host as the same user as gpupgrade since these are the [same commands that gpupgrade runs](https://github.com/greenplum-db/gpupgrade/blob/039e97551b4b7057b324be6a574ca04d278caf9b/greenplum/version.go#L57-L77). gpupgrade explicitly clears out the environment before running the commands.
- Locally on the coordinator host $GPHOME_SOURCE/bin/postgres --gp-version
- And remotely on each host with ssh -q <host> bash -c $GPHOME_SOURCE/bin/postgres --gp-version

**Comment by macbethDGPH** [comment]
There is:
```
gpadmin@mdw:~$ $GPHOME/bin/postgres --gp-version
postgres (Greenplum Database) 5.28.1 build dev-oss
gpadmin@mdw:~$ ssh sdw1 -q bash -c $GPHOME/bin/postgres --gp-version
/opt/gpdb/bin/postgres: error while loading shared libraries: libgpopt.so.3: cannot open shared object file: No such file or directory
gpadmin@mdw:~$ ssh sdw2 -q bash -c $GPHOME/bin/postgres --gp-version
/opt/gpdb/bin/postgres: error while loading shared libraries: libgpopt.so.3: cannot open shared object file: No such file or directory
```
But output changes when I use it:
```
gpadmin@mdw:~$ ssh -q sdw1 "bash --login -c '$GPHOME/bin/postgres --gp-version'"
postgres (Greenplum Database) 5.28.1 build dev-oss
gpadmin@mdw:~$ ssh -q sdw2 "bash --login -c '$GPHOME/bin/postgres --gp-version'"
postgres (Greenplum Database) 5.28.1 build dev-oss
```

**Comment by kalensk** [comment]
The obvious question is what is in either ~/.bash_profile, ~/.bash_login, and/or ~/.profile that is causing a difference between using `--login` and not using it since on initial glance there should not be any "external dependency" needed for getting `--gp-version`.

From the man page on BASH for `--login`:
> When bash is invoked as an interactive login shell, or as a non-interactive shell with the --login option, it first reads and executes commands from the file /etc/profile, if that file exists. After reading that file, it looks for ~/.bash_profile, ~/.bash_login, and ~/.profile, in that order, and reads and executes commands from the first one that exists and is readable. The --noprofile option may be used when the shell is started to inhibit this behavior.

**Comment by kalensk** [comment]
It looks like you are running GPDB version 5.28.1 with gpupgrade version 1.1.0. However, the _minimum_ supported version of GPDB for that version of gpupgrade is actually 5.28.12 as shown [here](https://github.com/greenplum-db/gpupgrade/blob/1.1.0/greenplum/allowed_gpdb_versions.go#L32-L35). Thus, you will have to update to that version or later with a strong recommendation to the latest version of 5X before proceeding with the upgrade process.


> postgres (Greenplum Database) 5.28.1 build dev-oss

> gpupgrade --version
Version: 1.1.0
Commit: b615d6f
Release: Open Source

**Comment by macbethDGPH** [comment]
Text in `.profile` and `.bashrc`, there are no `.bash_profile` and `.bash_login` in `/home/gpadmin/`.
```
gpadmin@mdw:~$ cat .profile 
if [ -f /etc/bashrc ]; then
        . /etc/bashrc   # --> Read /etc/bashrc, if present.
fi
source /opt/gpdb/greenplum_path.sh

export MASTER_DATA_DIRECTORY=/db/data/master/gpseg-1
export PATH=$PATH:.

export PGPORT=5432
export PGUSER=gpadmin
export PGDATABASE=postgres
gpadmin@mdw:~$ cat .bashrc 
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
source .profile
```

**Comment by macbethDGPH** [comment]
>  What happens when you ssh to sdw1 or sdw2 and manually run $GPHOME_SOURCE/bin/postgres --gp-version locally on that host? Does that provide any additional clues as to what might be going on?
It works correctly like at the mdw(master) host.

> Looks like libgpopt.so.3 might be related to gporca. Why is that occurring? And why does it not appear when using a login shell?
I will try to find out

**Comment by macbethDGPH** [comment]
> Looks like libgpopt.so.3 might be related to gporca. Why is that occurring? And why does it not appear when using a login shell?

I'm not sure, but I think it occurred because libgpopt.so.3 is located at `$GPHOME/lib/` directory. And if use `bash` without `--login` it will know nothing about `$GPHOME `

**Comment by kalensk** [comment]
One hypothesis is that you are using the OSS build of GPDB and gporca which might be setting the RPATH correctly for `libgpopt.so.3`. Can you explain in detail where and how you are building GPDB and gporca?

**Comment by BaiShaoqi** [comment]
Hi, @macbethDGPH   the oss build of gpdb5 does not set the RPATH correctly, so the only chance to find the dependency library correctly is setting GPHOME.
We already stopped vendoring gpdb5 oss build. i don't think we support any issues encountered from a gpdb5 oss build.

**Comment by kalensk** [comment]
To add to @BaiShaoqi, the enterprise version of GPDB 5 does not have this issue, and would successfully work with gpupgrade.

**Comment by kalensk** [comment]
The proper fix from the gpupgrade side is to check the versions using gRPC rather than ssh. I have made a story in our backlog. Hopefully, we can have time to work on this for our next release of gpupgrade.

**Comment by macbethDGPH** [comment]
> Hi, @macbethDGPH the oss build of gpdb5 does not set the RPATH correctly, so the only chance to find the dependency library correctly is setting GPHOME.
> We already stopped vendoring gpdb5 oss build. i don't think we support any issues encountered from a gpdb5 oss build.

**Comment by macbethDGPH** [comment]
z<c<z

**Comment by macbethDGPH** [comment]
> Hi, @macbethDGPH the oss build of gpdb5 does not set the RPATH correctly, so the only chance to find the dependency library correctly is setting GPHOME.
> We already stopped vendoring gpdb5 oss build. i don't think we support any issues encountered from a gpdb5 oss build.

But it is a issue with `gpupgrade` utility, not with `gpdb5`. Isn't it?

**Comment by kalensk** [comment]
> But it is a issue with gpupgrade utility, not with gpdb5. Isn't it?

Depends on how you look at it. I would say its primarily an issue with open source GPDB 5X. gpupgrade could be refactored to be more accepting of "broken" builds, which I have made note to update.

**Comment by kalensk** [comment]
@macbethDGPH 

We are addressing this issue in our code now and should have a fix in the next week or two on the main branch. This will be included in our next release of gpupgrade which will be roughly in the next 1-2 months or so.

As a quick workaround you could try running gpupgrade initialize with the hidden flag --skip-version-check. This is not recommended and only used for internal developer testing.

I hope this helps. Sorry for the delay as we are working on lots of other features and work.

**Comment by kalensk** [comment]
This has been addressed in our latest [release](https://github.com/greenplum-db/gpupgrade/releases) (1.2.0) which was released today. Please take a look and let us know. Closing this for now, but feel free to open with any additional information.
